;;; matugen-theme.el --- Dynamic standalone scientific theme generated from Matugen -*- lexical-binding: t -*-

;; Copyright (C) 2026 Diego

;; Author: Diego
;; Maintainer: Diego
;; Version: 1.0.0
;; Package-Requires: ((emacs "28.1"))
;; Keywords: themes, matugen, wayland, ricing

;;; Commentary:

;; This package provides a dynamic, standalone Emacs theme generated entirely
;; from Matugen colour palettes (typically used in Wayland environments).
;; 
;; It completely bypasses external theme dependencies. Instead, it reads your
;; primary Matugen color, calculates a mathematically precise "scientific wheel"
;; of complementary accent colors (Red, Green, Yellow, Blue, Magenta, Cyan),
;; and injects them directly into Emacs' syntax highlighting and Org mode.

;;; Code:

(require 'filenotify)
(require 'color)

(defgroup matugen-theme nil
  "Dynamic theme switcher based on Matugen colour palettes."
  :prefix "matugen-theme-")

(defcustom matugen-theme-colors-file (expand-file-name "~/.config/emacs/matugen-colors.conf")
  "Absolute path to the colour palette file generated by Matugen."
  :type 'file
  :group 'matugen-theme)

(defun matugen-theme--get-file-path ()
  "Return the Matugen file path. Fallbacks to dankcolors if the primary doesn't exist."
  (if (file-exists-p matugen-theme-colors-file)
      matugen-theme-colors-file
    (let ((fallback (expand-file-name "~/.config/ghostty/themes/dankcolors")))
      (if (file-exists-p fallback) fallback matugen-theme-colors-file))))

(defvar matugen-theme--file-watch-descriptor nil
  "Descriptor for the active file system watcher.")

(defun matugen-theme--read-palette ()
  "Parse the Matugen generated file and return an alist of colours."
  (let ((target-file (matugen-theme--get-file-path)))
    (when (file-exists-p target-file)
      (let ((colors nil))
        (with-temp-buffer
          (insert-file-contents target-file)
          (goto-char (point-min))
          (while (re-search-forward "^\\([a-z-]+\\) = \\(#[0-9a-fA-F]+\\)" nil t)
            (push (cons (intern (match-string 1)) (match-string 2)) colors))
          (goto-char (point-min))
          (while (re-search-forward "^palette = \\([0-9]+\\)=\\(#[0-9a-fA-F]+\\)" nil t)
            (push (cons (intern (format "palette-%s" (match-string 1))) (match-string 2)) colors)))
        colors))))

(defun matugen-theme--hex-to-rgb (hex)
  "Convert HEX color string to a list of (R G B) components from 0.0 to 1.0."
  (let ((r (/ (string-to-number (substring hex 1 3) 16) 255.0))
        (g (/ (string-to-number (substring hex 3 5) 16) 255.0))
        (b (/ (string-to-number (substring hex 5 7) 16) 255.0)))
    (list r g b)))

(defun matugen-theme--rgb-to-hex (rgb)
  "Convert list of (R G B) components from 0.0 to 1.0 back to a HEX string."
  (format "#%02x%02x%02x"
          (max 0 (min 255 (round (* (nth 0 rgb) 255))))
          (max 0 (min 255 (round (* (nth 1 rgb) 255))))
          (max 0 (min 255 (round (* (nth 2 rgb) 255))))))

(defun matugen-theme--mod-color (hex percent lighten)
  "Lighten or darken a HEX colour by PERCENT (0-100).
If LIGHTEN is non-nil, the colour is lightened; otherwise, darkened."
  (let* ((rgb (matugen-theme--hex-to-rgb hex))
         (hsl (apply #'color-rgb-to-hsl rgb))
         (h (nth 0 hsl))
         (s (nth 1 hsl))
         (l (nth 2 hsl))
         (new-l (if lighten (+ l (/ percent 100.0)) (- l (/ percent 100.0))))
         (clamped-l (max 0.0 (min 1.0 new-l)))
         (new-rgb (color-hsl-to-rgb h s clamped-l)))
    (matugen-theme--rgb-to-hex new-rgb)))

(defun matugen-theme--relative-luminance (r g b)
  "Calculate relative luminance."
  (let ((sR (if (<= r 0.03928) (/ r 12.92) (expt (/ (+ r 0.055) 1.055) 2.4)))
        (sG (if (<= g 0.03928) (/ g 12.92) (expt (/ (+ g 0.055) 1.055) 2.4)))
        (sB (if (<= b 0.03928) (/ b 12.92) (expt (/ (+ b 0.055) 1.055) 2.4))))
    (+ (* 0.2126 sR) (* 0.7152 sG) (* 0.0722 sB))))

(defun matugen-theme--is-dark-color (hex)
  "Return non-nil if HEX is a dark colour based on relative luminance."
  (let* ((rgb-hex (matugen-theme--hex-to-rgb hex))
         (r (nth 0 rgb-hex))
         (g (nth 1 rgb-hex))
         (b (nth 2 rgb-hex)))
    (< (matugen-theme--relative-luminance r g b) 0.5)))

(defun matugen-theme--contrast-ratio (hex1 hex2)
  "Calculate WCAG contrast ratio between two HEX colours."
  (let* ((rgb1 (matugen-theme--hex-to-rgb hex1))
         (rgb2 (matugen-theme--hex-to-rgb hex2))
         (lum1 (matugen-theme--relative-luminance (nth 0 rgb1) (nth 1 rgb1) (nth 2 rgb1)))
         (lum2 (matugen-theme--relative-luminance (nth 0 rgb2) (nth 1 rgb2) (nth 2 rgb2))))
    (/ (+ (max lum1 lum2) 0.05) (+ (min lum1 lum2) 0.05))))

(defun matugen-theme--ensure-contrast (hex bg-hex is-dark target-ratio)
  "Adjust HEX until it has at least TARGET-RATIO contrast against BG-HEX."
  (let ((current-hex hex)
        (ratio (matugen-theme--contrast-ratio hex bg-hex))
        (iterations 0)
        (max-iterations 20))
    (while (and (< ratio target-ratio) (< iterations max-iterations))
      (setq current-hex (matugen-theme--mod-color current-hex 5 is-dark))
      (setq ratio (matugen-theme--contrast-ratio current-hex bg-hex))
      (setq iterations (1+ iterations)))
    current-hex))

(defun matugen-theme--hue-distance (h1 h2)
  "Calculate the shortest distance between two hues on the 360 circle."
  (let ((diff (abs (- h1 h2))))
    (if (> diff 0.5) (- 1.0 diff) diff)))

(defun matugen-theme--generate-scientific-wheel (seed-hex is-dark)
  "Generate a 6-color wheel scientifically offset from SEED-HEX."
  (let* ((seed-rgb (matugen-theme--hex-to-rgb seed-hex))
         (seed-hsl (apply #'color-rgb-to-hsl seed-rgb))
         (h (nth 0 seed-hsl))
         ;; Target saturations and lightness for coding visibility
         (s (if is-dark 0.75 0.85))
         (l (if is-dark 0.70 0.40))
         ;; Hue targets for standard syntax: Red, Green, Yellow, Blue, Magenta, Cyan
         (hue-targets '(("red" . 0.0)
                        ("yellow" . 0.16)
                        ("green" . 0.33)
                        ("cyan" . 0.5)
                        ("blue" . 0.66)
                        ("magenta" . 0.83)))
         (wheel nil))
    
    (dolist (target hue-targets)
      (let* ((name (car target))
             (target-h (cdr target))
             ;; If the seed hue is very close to this target hue, use the seed's exact hue
             (final-h (if (< (matugen-theme--hue-distance h target-h) 0.08) h target-h))
             (rgb (color-hsl-to-rgb final-h s l))
             (hex (matugen-theme--rgb-to-hex rgb)))
        (push (cons (intern name) hex) wheel)))
    wheel))

(deftheme matugen "Dynamic standalone scientific Matugen theme.")

;;;###autoload
(defun matugen-theme-reload ()
  "Reload the Matugen palette and generate the standalone dynamic theme."
  (interactive)
  (let ((colors (matugen-theme--read-palette)))
    (when colors
      (let* ((bg-raw (or (cdr (assoc 'background colors)) "#000000"))
             (is-dark (matugen-theme--is-dark-color bg-raw))
             
             (bg (if is-dark bg-raw (or (cdr (assoc 'background colors)) "#ffffff")))
             (fg-main (or (cdr (assoc 'foreground colors)) (if is-dark "#ffffff" "#000000")))
             
             ;; We use palette-1 or foreground as the 'seed' color to generate the wheel
             (seed (or (cdr (assoc 'palette-1 colors)) fg-main))
             (wheel (matugen-theme--generate-scientific-wheel seed is-dark))
             
             ;; We ensure all syntax colors have perfect contrast against the background
             (red (matugen-theme--ensure-contrast (cdr (assoc 'red wheel)) bg is-dark 4.5))
             (green (matugen-theme--ensure-contrast (cdr (assoc 'green wheel)) bg is-dark 4.5))
             (yellow (matugen-theme--ensure-contrast (cdr (assoc 'yellow wheel)) bg is-dark 4.5))
             (blue (matugen-theme--ensure-contrast (cdr (assoc 'blue wheel)) bg is-dark 4.5))
             (magenta (matugen-theme--ensure-contrast (cdr (assoc 'magenta wheel)) bg is-dark 4.5))
             (cyan (matugen-theme--ensure-contrast (cdr (assoc 'cyan wheel)) bg is-dark 4.5))
             
             ;; UI shades
             (bg-alt (matugen-theme--mod-color bg 4 is-dark))
             (bg-active (matugen-theme--mod-color bg 8 is-dark))
             (bg-region (matugen-theme--mod-color bg 15 is-dark))
             (fg-dim (matugen-theme--mod-color fg-main 25 (not is-dark))))

        ;; Clear existing theme properties
        (put 'matugen 'theme-properties nil)
        
        ;; Map colors directly to core Emacs faces and Org mode
        (custom-theme-set-faces
         'matugen
         ;; Core
         `(default ((t (:background ,bg :foreground ,fg-main))))
         `(fringe ((t (:background ,bg))))
         `(cursor ((t (:background ,seed))))
         `(region ((t (:background ,bg-region))))
         `(hl-line ((t (:background ,bg-alt))))
         
         ;; Font-lock (Syntax Highlighting)
         `(font-lock-keyword-face ((t (:foreground ,magenta :weight bold))))
         `(font-lock-type-face ((t (:foreground ,yellow))))
         `(font-lock-string-face ((t (:foreground ,green))))
         `(font-lock-constant-face ((t (:foreground ,cyan))))
         `(font-lock-variable-name-face ((t (:foreground ,red))))
         `(font-lock-function-name-face ((t (:foreground ,blue))))
         `(font-lock-comment-face ((t (:foreground ,fg-dim :slant italic))))
         `(font-lock-builtin-face ((t (:foreground ,magenta))))
         `(font-lock-preprocessor-face ((t (:foreground ,cyan))))
         
         ;; Org Mode
         `(org-level-1 ((t (:foreground ,blue :weight bold :height 1.2))))
         `(org-level-2 ((t (:foreground ,magenta :weight bold :height 1.1))))
         `(org-level-3 ((t (:foreground ,cyan :weight bold))))
         `(org-level-4 ((t (:foreground ,yellow :weight bold))))
         `(org-level-5 ((t (:foreground ,green :weight bold))))
         `(org-level-6 ((t (:foreground ,red :weight bold))))
         `(org-level-7 ((t (:foreground ,blue))))
         `(org-level-8 ((t (:foreground ,magenta))))
         `(org-document-title ((t (:foreground ,fg-main :weight bold :height 1.3))))
         `(org-document-info ((t (:foreground ,cyan))))
         `(org-block ((t (:background ,bg-alt))))
         `(org-block-begin-line ((t (:foreground ,fg-dim :background ,bg-alt :slant italic))))
         `(org-block-end-line ((t (:foreground ,fg-dim :background ,bg-alt :slant italic))))
         `(org-meta-line ((t (:foreground ,fg-dim :slant italic))))
         `(org-code ((t (:foreground ,yellow :background ,bg-alt))))
         `(org-verbatim ((t (:foreground ,green :background ,bg-alt))))
         
         ;; UI and Modeline
         `(mode-line ((t (:background ,bg-active :foreground ,fg-main))))
         `(mode-line-inactive ((t (:background ,bg-alt :foreground ,fg-dim))))
         `(minibuffer-prompt ((t (:foreground ,cyan :weight bold))))
         `(vertical-border ((t (:foreground ,bg-active))))
         
         ;; Doom Emacs specific faces
         `(doom-dashboard-menu-title ((t (:foreground ,blue :weight bold))))
         `(doom-dashboard-menu-desc ((t (:foreground ,fg-dim))))
         `(solaire-default-face ((t (:background ,bg :foreground ,fg-main))))
         `(solaire-hl-line-face ((t (:background ,bg-alt))))
         `(solaire-org-hide-face ((t (:background ,bg :foreground ,bg))))
         )
         
        ;; Force Emacs frame parameter to match the theme
        (set-frame-parameter nil 'background-mode (if is-dark 'dark 'light))
        (set-terminal-parameter nil 'background-mode (if is-dark 'dark 'light))
        
        ;; Purge old themes and load our standalone theme
        (mapc #'disable-theme custom-enabled-themes)
        (enable-theme 'matugen)
        
        (when (boundp 'doom-theme)
          (setq doom-theme 'matugen))
          
        (when (fboundp 'doom/reload-theme)
          (doom/reload-theme))
          
        (when (featurep 'solaire-mode)
          (solaire-global-mode -1)
          (solaire-global-mode 1))
        
        (message "Matugen-Theme: Loaded standalone scientific theme.")))))

(defun matugen-theme--watcher-callback (event)
  "Callback executed when the designated colour file changes."
  (let ((file (nth 2 event)))
    (when (and (stringp file)
               (string= (file-name-nondirectory file)
                        (file-name-nondirectory (matugen-theme--get-file-path))))
      (matugen-theme-reload))))

(defun matugen-theme-mode-disable ()
  "Disable the file watcher."
  (when matugen-theme--file-watch-descriptor
    (file-notify-rm-watch matugen-theme--file-watch-descriptor)
    (setq matugen-theme--file-watch-descriptor nil)))

;;;###autoload
(define-minor-mode matugen-theme-mode
  "Global minor mode to synchronise Emacs with Matugen generated palettes."
  :global t
  :lighter nil
  (if matugen-theme-mode
      (let ((dir (file-name-directory (matugen-theme--get-file-path))))
        (when (file-exists-p dir)
          ;; Initial load delayed until UI frame is completely drawn
          (if (display-graphic-p)
              (run-with-idle-timer 0.1 nil #'matugen-theme-reload)
            (if after-init-time
                (matugen-theme-reload)
              (add-hook 'emacs-startup-hook (lambda () (run-with-idle-timer 0.1 nil #'matugen-theme-reload)))))
          
          ;; Setup file watcher
          (setq matugen-theme--file-watch-descriptor
                (when (fboundp 'file-notify-add-watch)
                  (file-notify-add-watch dir
                                         '(change attribute-change)
                                         #'matugen-theme--watcher-callback)))))
    (matugen-theme-mode-disable)))

(provide 'matugen-theme)
;;; matugen-theme.el ends here
